# app.py
import streamlit as st
import pandas as pd

# --------------------------------------------------
# Page Configuration
# --------------------------------------------------
st.set_page_config(
    page_title="Twitter Hashtag Topic Modeling",
    page_icon="📊",
    layout="wide"
)

# --------------------------------------------------
# Sidebar
# --------------------------------------------------
st.sidebar.title("Navigation")
section = st.sidebar.radio(
    "Go to",
    [
        "Project Overview",
        "Trending Hashtags",
        "Topic Modeling Results",
        "Dataset Preview"
    ]
)

# --------------------------------------------------
# Load Data (once)
# --------------------------------------------------
@st.cache_data
def load_data():
    return pd.read_csv("data/cleaned_tweets.csv")

df = load_data()

# --------------------------------------------------
# Project Overview
# --------------------------------------------------
if section == "Project Overview":
    st.title("Twitter Hashtag Topic Modeling using NLP")

    st.markdown(
        """
        This project analyzes Twitter hashtags using **Natural Language Processing (NLP)** 
        techniques to identify **trending discussion topics**.

        ### Key Highlights
        - Hashtag extraction and text preprocessing
        - Topic discovery using **Latent Dirichlet Allocation (LDA)**
        - **Automatic topic labeling** using Large Language Models (LLMs)
        - Interactive visualization via **Streamlit**
        - Architecture supports real-time Twitter (X) API ingestion

        This application presents **precomputed results** generated by the NLP pipeline.
        """
    )

# --------------------------------------------------
# Trending Hashtags
# --------------------------------------------------
elif section == "Trending Hashtags":
    st.title("Trending Hashtags Analysis")

    st.markdown(
        """
        The visualization below shows the **top trending hashtags** based on frequency.
        This provides an initial understanding of dominant themes present in the dataset.
        """
    )

    st.image(
        "outputs/plots/top_hashtags.png",
        caption="Top Trending Hashtags",
        use_column_width=True
    )

# --------------------------------------------------
# Topic Modeling Results
# --------------------------------------------------
elif section == "Topic Modeling Results":
    st.title("Discovered Topics and Labels")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("LDA Topic Keywords")
        st.markdown(
            "These are the raw topics discovered by the **LDA model**, "
            "represented by their most important keywords."
        )
        with open("outputs/topics.txt", "r") as f:
            st.text(f.read())

    with col2:
        st.subheader("Automatically Labeled Topics")
        st.markdown(
            "These labels are generated **automatically using Large Language Models**, "
            "making the topics easier to interpret."
        )
        with open("outputs/topic_labels.txt", "r") as f:
            st.text(f.read())

# --------------------------------------------------
# Dataset Preview
# --------------------------------------------------
elif section == "Dataset Preview":
    st.title("Cleaned Hashtag Dataset")

    st.markdown(
        """
        Below is a preview of the **cleaned hashtag text** used for topic modeling.
        This data is generated after preprocessing and noise removal.
        """
    )

    st.dataframe(
        df[["clean_text"]].head(50),
        use_container_width=True
    )

# --------------------------------------------------
# Footer
# --------------------------------------------------
st.markdown("---")
st.markdown(
    "**Developed by Ronak Vadher and Tanishq Bhalekar**  \n"
    "NLP Project | Twitter Hashtag Topic Modeling"
)
